# Generated by Django 5.1.2 on 2024-11-19 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_created_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='telefono'),
        ),
    ]
