# Generated by Django 5.1.2 on 2024-11-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_rut_alter_profile_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Rut'),
        ),
    ]
