# Generated by Django 5.1.2 on 2024-11-26 02:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='La dirección contiene caracteres no válidos', regex='^[a-zA-Z0-9\\s,.-]+$')], verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='users/usuario_defecto.jpg', upload_to='users/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'], message='Solo se permiten imágenes JPG o PNG')], verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='La localidad solo debe contener letras', regex='^[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]+$')], verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido (Ej: 12.345.678-9)', regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$')], verbose_name='Rut'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número válido (+56912345678)', regex='^\\+?569\\d{8}$')], verbose_name='Teléfono'),
        ),
    ]
