# Generated by Django 5.1.2 on 2024-11-02 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(limit_choices_to={'groups__name': 'clientes'}, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_registrado', to=settings.AUTH_USER_MODEL, verbose_name='cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicios', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'solicitud de servicio',
                'verbose_name_plural': 'solicitudes de servicios',
            },
        ),
    ]
