# Generated by Django 5.1.2 on 2024-11-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registroservicio_enabled_asistencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='n_procedimientos',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero de procedimientos'),
        ),
    ]
