# Generated by Django 5.1.2 on 2024-11-03 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_servicios_n_procedimientos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='n_procedimientos',
            field=models.PositiveIntegerField(default=0, verbose_name='Numero de sesiones'),
        ),
        migrations.CreateModel(
            name='infocliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen')),
                ('odontograma', models.FileField(blank=True, null=True, upload_to='odontogramas/', verbose_name='Odontograma')),
                ('cliente', models.ForeignKey(limit_choices_to={'groups__name': 'clientes'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicios', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
    ]
