# Generated by Django 5.1.2 on 2024-11-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicios_n_procedimientos_infocliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicios',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitud de Servicio'), ('P', 'En progreso'), ('F', 'Finalizado')], default='S', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='n_procedimientos',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de sesiones'),
        ),
    ]
