# Generated by Django 5.1.2 on 2024-11-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_infocliente_imagen_infocliente_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroservicio',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
    ]
