# Generated by Django 5.1.2 on 2024-11-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_registroservicio_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroservicio',
            name='odontograma',
            field=models.ImageField(blank=True, null=True, upload_to='odontogramas/'),
        ),
    ]
