# Generated by Django 5.1.2 on 2024-11-23 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_mouth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de la Reserva')),
                ('hora', models.TimeField(verbose_name='Hora de la Reserva')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'clientes'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('profesional', models.ForeignKey(limit_choices_to={'groups__name': 'profesionales'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservas_profesional', to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'unique_together': {('profesional', 'fecha', 'hora')},
            },
        ),
    ]
