# Generated by Django 5.1.2 on 2024-11-23 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission', models.TextField(verbose_name='Misión')),
                ('vision', models.TextField(verbose_name='Visión')),
                ('values', models.TextField(verbose_name='Valores')),
                ('contact_info', models.TextField(verbose_name='Información de Contacto')),
                ('images', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Imágenes')),
            ],
            options={
                'verbose_name': 'Acerca de',
                'verbose_name_plural': 'Acerca de',
            },
        ),
    ]
