# Generated by Django 5.1.2 on 2024-11-24 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_servicios_cliente_alter_servicios_profesional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pagada', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('profesional', models.ForeignKey(limit_choices_to={'groups__name': 'profesionales'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Profesional')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horariodisponible')),
            ],
        ),
    ]
