# Generated by Django 5.1.2 on 2024-11-24 05:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_horariodisponible_consulta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='horario',
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
