# Generated by Django 5.1.2 on 2024-11-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_consulta_preference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='telefono',
            field=models.CharField(max_length=12),
        ),
    ]
