# Generated by Django 5.1.2 on 2024-12-02 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_registroservicio_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0, 'El precio no puede ser negativo')], verbose_name='Precio'),
        ),
    ]
