# Generated by Django 5.1.2 on 2024-12-03 01:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_consulta_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'El nombre debe tener al menos 3 caracteres')])),
                ('descripcion', models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10, 'La descripción debe tener al menos 10 caracteres')])),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.AlterField(
            model_name='servicios',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('P', 'Progresso'), ('F', 'Finalizado')], default='S', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.especialidad', verbose_name='Especialidad'),
        ),
    ]
